export const USER_SIGNED_IN = "USER_SIGNED_IN";
export const USER_SIGNED_UP = "USER_SIGNED_UP";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const CLEAR_ERR_MSG = "CLEAR_ERR_MSG";
export const FINISH_LOCAL_TOKEN_LOADING = "FINISH_LOCAL_TOKEN_LOADING";

export const SET_LOADING = "SET_LOADING";
export const CLEAR_LOADING = "CLEAR_LOADING";
